### ISSUE TITLE
Rename discrete to absolute in axis scaling

### ISSUE THREAD

**Issue by CorneliaAuerPIK** [SensesProject/gems#18]

**Comment by fidelthomet** [comment]
can do, but wouldn't `relative` be more appropriate?

**Comment by fidelthomet** [comment]
can do. but wouldn't `relative` be more appropriate?

**Comment by CorneliaAuerPIK** [comment]
Hey, relative == synchronized (they are all relative to each others in the same coordinate system), absolute == opposite of relative (every chart stands absolute for itself)
Could be that I am already crazy but I am rather confident on that.

**Comment by fidelthomet** [comment]
I'd argue that `relative` means relative to the range of values in every panel while absolute means there's a single (i.e.; absolute) range that goes for every panel

**Comment by fidelthomet** [comment]
but happy to go with `synced` and `absolute` for now, and change things if people get confused

**Comment by CorneliaAuerPIK** [comment]
great, best pragmatic solution
