### ISSUE TITLE
Könnte ich unter dem Auswahlfeld text haben?

### ISSUE THREAD

**Issue by CorneliaAuerPIK** [SensesProject/gems#28]
Eigentlich bietet sich Text fast unter dem Perspective Feld an. Wäre das viel Aufwand das zu ermöglichen?

![image](https://user-images.githubusercontent.com/29375193/75559829-77a80f00-5a44-11ea-845c-05909a81eb94.png)

**Comment by CorneliaAuerPIK** [comment]
Sonst muss ich oben quasi immer die gesamte info geben. 
Prinzipiell würde oben schon ca 2 Zeilen Üblick 
Unterhalb der Perspective ca 4 zeilen detail 
Let me know, ich weiß die Anfrage kommt spät.

**Comment by fidelthomet** [comment]
new property `text` in default for default or in `options` to relate to `perspective` see example config → 
```
{
  "title": "Example Options",
  "description": "yes options, no dictionary, no string interpolation",
  "default": {
    "runs": […],
    "regions": ["World"],
→   "text": "default text"
  },
  "dropdowns": [{
    "label": "Perspective",
    "options": [{
      "label": "AFOLU Emissions",
      "variables": [
        "Emissions|CO2|AFOLU",
        "Emissions|CH4|AFOLU",
        "Emissions|N2O|AFOLU"
      ],
→     "text": "option 1 text"
    }, {
      "label": "AFOLU Sequestration",
      "variables": [
        "Carbon Sequestration|Land Use|Afforestation"
      ],
→     "text": "option 2 text"
    }]
  }]
}
```
