### ISSUE TITLE
Funnel zigzag

### ISSUE THREAD

**Issue by CorneliaAuerPIK** [SensesProject/gems#29]
For a specific set of scenarios the funnels produce zigzag.
Example debug_finance-uncertainty
![image](https://user-images.githubusercontent.com/29375193/75607520-4852da00-5af8-11ea-8739-7ce90fd2e852.png)

**Comment by fidelthomet** [comment]
that's most likely due to some of those scenarios have 5 year intervals until 2060, while others have not… i'll come up with some way to interpolate those values later or tomorrow

**Comment by fidelthomet** [comment]
fix is a bit hacky and might not cover some edge cases. should be rewritten at some point → #32

**Comment by CorneliaAuerPIK** [comment]
would it be easier if you just ignore all years that end at a 5 (instead of interpolating)? or maybe you did exactly this. 
in any case, i would have no problem if we just drop this information and you only work steps of 10 or more years (very rarely it is only 2050 2060 2070 2100)
