### ISSUE TITLE
Funnel variable replacement

### ISSUE THREAD

**Issue by CorneliaAuerPIK** [SensesProject/gems#30]
The variable replacement in the funnel runs is not activated. [Please note: this is not so burning like the zigzag, i can also restrict to one temperature boundary if necessary]
  "funnel": [
      ["REMIND-MAgPIE 1.7-3.0", "CD-LINKS_NoPolicy"],
      ["REMIND-MAgPIE 1.7-3.0", "CD-LINKS_NPi2020_${warming}"]
     ],
$warming has no effect 
in runs it has an effect 
 "runs": [
      ["AIM/CGE 2.0", "SSP2-Baseline"],
      ["REMIND-MAgPIE 1.7-3.0", "CD-LINKS_NPi2020_${warming}"] 
    ],
I assume it only has to be activated.
Example: debug_funnel-variableReplacement

**Comment by fidelthomet** [comment]
yes, should be an easy fix
