### ISSUE TITLE
Choice of reference scenario possible? 

### ISSUE THREAD

**Issue by CorneliaAuerPIK** [SensesProject/gems#31]
I would like to provide a dropdown where the user can pick P1- P4. But currently I am struggeling to define a run as a variable, because it consists of two strings. 
Is there a chance to use escape sequences to define strings within a string? 
<snip>
 "label": "Reference scenario",
    "options": [{
      "label": "P1 - Low energy demand",
      "refRun": "?XXX"
</snip>
could refRun be something like, (quotation marks escaped by\): 
"\"MESSAGEix-GLOBIOM 1.0\", \"LowEnergyDemand\" "?
Or maybe you have a more simple idea, how such a choice could be realized..?

**Comment by CorneliaAuerPIK** [comment]
Just in case 
debug_referenceScenario as example

**Comment by fidelthomet** [comment]
it's possible in the same way as setting runs works. see debug_referenceScenario as reference
