### ISSUE TITLE
Display is all empty :o Wrong comma somewhere?!

### ISSUE THREAD

**Issue by CorneliaAuerPIK** [SensesProject/gems#33]
Pulling the changes made GEMs all empty (not even text). I did a reset to my version before the merge and things were back again. So it must be somewhere in the code I pulled. 
Surprisingly the braces still work, it is only the GEMs.
 i am sure, it is a wrong comma somewhere, but would be great to have things back :))
![image](https://user-images.githubusercontent.com/29375193/75615169-d5218600-5b40-11ea-9c30-91bfcd0dacaa.png)

**Comment by fidelthomet** [comment]
sorry, was introduced by resolving #30 which basically required `reference` and `funnel` to be defined in the config… now it works again
