### ISSUE TITLE
Can I have primitive HTML/ markdown in the description texts?

### ISSUE THREAD

**Issue by CorneliaAuerPIK** [SensesProject/gems#35]
How much of an effort would it be to have some primitive kind of markdown in the description. 
Breaks and bullet points would already be great. 
![image](https://user-images.githubusercontent.com/29375193/75627871-5118de00-5bd4-11ea-9468-63796c2c6596.png)

**Comment by fidelthomet** [comment]
markdown would be possible and relatively easy to implement… html is error-prone and likely to cause unwanted side effects / security issues

**Comment by fidelthomet** [comment]
both, md and html is now supported. html gets sanitized (for details → https://github.com/cure53/DOMPurify)

**Comment by fidelthomet** [comment]
example https://github.com/SensesProject/gems/blob/master/public/configs/example-options-simple.json
