### ISSUE TITLE
dict does not apply to meta info

### ISSUE THREAD

**Issue by CorneliaAuerPIK** [SensesProject/gems#36]
not so urgent, but that we don't forget
dict:
    "REMIND-MAgPIE 1.7-3.0 | PEP_1p5C_full_NDC": "REMIND-MAgPIE - PEP 1.5°C NDC, full CDR availibility",
oben richtig
![image](https://user-images.githubusercontent.com/29375193/75628259-807d1a00-5bd7-11ea-9be3-6425088f0c59.png)
unten nicht da
![image](https://user-images.githubusercontent.com/29375193/75628251-6e02e080-5bd7-11ea-8907-2c7a658a9fa2.png)

**Comment by fidelthomet** [comment]
hm… you'd need to set more dict entries like 
```
"PEP_1p5C_full_NDC": "PEP 1.5°C NDC, full CDR availibility"
```
