### ISSUE TITLE
Mini but important: Transition risk instead of fossil fuels risk

### ISSUE THREAD

**Issue by CorneliaAuerPIK** [SensesProject/gems#37]
Somehow in the menu it says 'fossil fuels risk' despite saying 'transition risk' in the code
![image](https://user-images.githubusercontent.com/29375193/75631457-4b7ec080-5bf3-11ea-85b1-a8992658a0dc.png)

code snippet in gems.json:
 "id": "transition-risk",
  "dir": "transition-risk",
  "gems": [
    {"id": "finance-wyman-indicators_fossilEnergy", .....

**Comment by fidelthomet** [comment]
if you use `id` the brace is linked to the module with the same `id` and the name is taken from https://github.com/SensesProject/share/tree/master/settings to ensure consistency… if you want to create a brace which is detached you can use `name` instead of id

**Comment by CorneliaAuerPIK** [comment]
But then it would be detached from the learn module and not linked in the toolkit and portals?

**Comment by fidelthomet** [comment]
theoretically it would be possible to have both, but from an ux perspective I think it's quite important to keep the name as it helps with orientation
