### ISSUE TITLE
optional: bind scenario selection to specific perspective /exploration question 

### ISSUE THREAD

**Issue by CorneliaAuerPIK** [SensesProject/gems#38]
for one perspective / exploration question I want to show riskfactor pathways, for another perspective I need to show model data. this leads to a long list of scenarios that are partially not shown. 
could i bind a scenario selection to a perspective choice? example test_scenario_perspective_choice

doesn't need to be, but would be cool. alternatively we could also filter scenarios that are currently not shown... whatever works.

![image](https://user-images.githubusercontent.com/29375193/75631695-5fc3bd00-5bf5-11ea-8915-bfb545d3d566.png)
![image](https://user-images.githubusercontent.com/29375193/75631702-6fdb9c80-5bf5-11ea-83cc-c3fcea7511cb.png)

**Comment by fidelthomet** [comment]
this is possible…
get rid of 

```
"runs": [
  ["$scenarios"]
],
```

and replace `scenarios` in options with `runs`

**Comment by CorneliaAuerPIK** [comment]
Yeah, party hard!! 💃 :D
