### ISSUE TITLE
can I have a line break after the exploration question?

### ISSUE THREAD

**Issue by CorneliaAuerPIK** [SensesProject/gems#40]
it would be good if the exploration question would be by definition with a line break (or as a hacky version, the first variable option?!)
The thing is that other drop-downs jump up and down, depending on the length of the question.
i know it is crazy one day before the workshop, but i just put it here, maybe you find time

**Comment by CorneliaAuerPIK** [comment]
![image](https://user-images.githubusercontent.com/29375193/75703069-09b74e00-5cb7-11ea-9f76-b5b00dc86861.png)

**Comment by fidelthomet** [comment]
tricky since the first option doesn’t have to be like this and a solution to this issue should be future proof. so, sorry no quick fix :/

**Comment by CorneliaAuerPIK** [comment]
already thought so. no trouble, we just leave it in here
